export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_AUTHORS_PHOTOS = 'FETCH_AUTHORS_PHOTOS';
export const FETCH_AUTHORS_PROFILE = 'FETCH_AUTHORS_PROFILE';
export const FETCH_AUTHORS_RESET = 'FETCH_AUTHORS_RESET';

